services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: architecture-nginx
    ports:
      - "60080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./laravel/public:/var/www/project/public
    depends_on:
      - php
    networks:
      - architecture-network

  mysql:
    image: mysql:8.4
    container_name: architecture-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=architecture
    ports:
      - "63306:3306"
    volumes:
      - architecture-mysql-data:/var/lib/mysql
    networks:
      - architecture-network
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: architecture-php
    volumes:
      - ./laravel:/var/www/project
    depends_on:
      - mysql
      # - redis
    networks:
      - architecture-network

  # redis:
  #   image: redis:7.2-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - architecture-network

volumes:
  architecture-mysql-data:
    driver: local

networks:
  architecture-network:
    driver: bridge
